//
// Generated file, do not edit! Created by nedtool 4.6 from src/node/communication/mac/dsmac/DSMACPacket.msg.
//

#ifndef _DSMACPACKET_M_H_
#define _DSMACPACKET_M_H_

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0406
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "MacPacket_m.h"
// }}

/**
 * Enum generated from <tt>src/node/communication/mac/dsmac/DSMACPacket.msg:19</tt> by nedtool.
 * <pre>
 * enum DSMACPacket_type
 * {
 * 
 *     MAC_DSMAC_BEACON_PACKET = 1001;
 *     MAC_DSMAC_ASSOCIATE_PACKET = 1002;
 *     MAC_DSMAC_DATA_PACKET = 1003;
 *     MAC_DSMAC_ACK_PACKET = 1004;
 *     MAC_DSMAC_GTS_REQUEST_PACKET = 1005;
 * }
 * </pre>
 */
enum DSMACPacket_type {
    MAC_DSMAC_BEACON_PACKET = 1001,
    MAC_DSMAC_ASSOCIATE_PACKET = 1002,
    MAC_DSMAC_DATA_PACKET = 1003,
    MAC_DSMAC_ACK_PACKET = 1004,
    MAC_DSMAC_GTS_REQUEST_PACKET = 1005
};

/**
 * Struct generated from src/node/communication/mac/dsmac/DSMACPacket.msg:27 by nedtool.
 */
struct DSMACGTSspec
{
    DSMACGTSspec();
    int owner;
    int start;
    int length;
};

void doPacking(cCommBuffer *b, DSMACGTSspec& a);
void doUnpacking(cCommBuffer *b, DSMACGTSspec& a);

/**
 * Class generated from <tt>src/node/communication/mac/dsmac/DSMACPacket.msg:33</tt> by nedtool.
 * <pre>
 * packet DSMACPacket extends MacPacket
 * {
 *     int DSMACPacketType @enum(DSMACPacket_type);
 *     int leaderNodeid;
 *     int srcID;
 *     int dstID;
 *     int seqNum;
 * 
 *     // those fields belong to beacon packet (MAC_DSMAC_BEACON_PACKET)
 *     int beaconOrder;
 *     int frameOrder;
 *     int BSN;
 *     int CAPlength;
 *     int GTSlength;
 *     DSMACGTSspec GTSlist[];
 * }
 * </pre>
 */
class DSMACPacket : public ::MacPacket
{
  protected:
    int DSMACPacketType_var;
    int leaderNodeid_var;
    int srcID_var;
    int dstID_var;
    int seqNum_var;
    int beaconOrder_var;
    int frameOrder_var;
    int BSN_var;
    int CAPlength_var;
    int GTSlength_var;
    DSMACGTSspec *GTSlist_var; // array ptr
    unsigned int GTSlist_arraysize;

  private:
    void copy(const DSMACPacket& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DSMACPacket&);

  public:
    DSMACPacket(const char *name=NULL, int kind=0);
    DSMACPacket(const DSMACPacket& other);
    virtual ~DSMACPacket();
    DSMACPacket& operator=(const DSMACPacket& other);
    virtual DSMACPacket *dup() const {return new DSMACPacket(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDSMACPacketType() const;
    virtual void setDSMACPacketType(int DSMACPacketType);
    virtual int getLeaderNodeid() const;
    virtual void setLeaderNodeid(int leaderNodeid);
    virtual int getSrcID() const;
    virtual void setSrcID(int srcID);
    virtual int getDstID() const;
    virtual void setDstID(int dstID);
    virtual int getSeqNum() const;
    virtual void setSeqNum(int seqNum);
    virtual int getBeaconOrder() const;
    virtual void setBeaconOrder(int beaconOrder);
    virtual int getFrameOrder() const;
    virtual void setFrameOrder(int frameOrder);
    virtual int getBSN() const;
    virtual void setBSN(int BSN);
    virtual int getCAPlength() const;
    virtual void setCAPlength(int CAPlength);
    virtual int getGTSlength() const;
    virtual void setGTSlength(int GTSlength);
    virtual void setGTSlistArraySize(unsigned int size);
    virtual unsigned int getGTSlistArraySize() const;
    virtual DSMACGTSspec& getGTSlist(unsigned int k);
    virtual const DSMACGTSspec& getGTSlist(unsigned int k) const {return const_cast<DSMACPacket*>(this)->getGTSlist(k);}
    virtual void setGTSlist(unsigned int k, const DSMACGTSspec& GTSlist);
};

inline void doPacking(cCommBuffer *b, DSMACPacket& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, DSMACPacket& obj) {obj.parsimUnpack(b);}


#endif // ifndef _DSMACPACKET_M_H_

